# Site settings
destination: ./docs
exclude: ["docs/"]
title: Chuanqi TAN
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chuanqi.name" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
